import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  // Documentation sidebar with custom labels
  docsSidebar: [
    'index',
    {
      type: 'category',
      label: 'Getting Started',
      items: [{type: 'autogenerated', dirName: 'getting-started'}],
    },
    {
      type: 'category',
      label: 'Installation',
      items: [{type: 'autogenerated', dirName: 'installation'}],
    },
    {
      type: 'category',
      label: 'Accounts',
      items: [{type: 'autogenerated', dirName: 'accounts'}],
    },
    {
      type: 'category',
      label: 'Configuration',
      items: [{type: 'autogenerated', dirName: 'configuration'}],
    },
    {
      type: 'category',
      label: 'Sending',
      items: [{type: 'autogenerated', dirName: 'sending'}],
    },
    {
      type: 'category',
      label: 'Receiving',
      items: [{type: 'autogenerated', dirName: 'receiving'}],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [{type: 'autogenerated', dirName: 'api-reference'}],
    },
    {
      type: 'category',
      label: 'Integrations',
      items: [{type: 'autogenerated', dirName: 'integrations'}],
    },
    {
      type: 'category',
      label: 'Advanced',
      items: [{type: 'autogenerated', dirName: 'advanced'}],
    },
    {
      type: 'category',
      label: 'Deployment',
      items: [{type: 'autogenerated', dirName: 'deployment'}],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [{type: 'autogenerated', dirName: 'reference'}],
    },
    {
      type: 'category',
      label: 'Comparison',
      items: [{type: 'autogenerated', dirName: 'comparison'}],
    },
    {
      type: 'category',
      label: 'Support',
      items: [{type: 'autogenerated', dirName: 'support'}],
    },
    {
      type: 'category',
      label: 'Troubleshooting',
      items: [{type: 'autogenerated', dirName: 'troubleshooting'}],
    },
  ],

  // API Reference sidebar - generated by OpenAPI plugin
  apiSidebar: [
    {
      type: 'autogenerated',
      dirName: 'api',
    },
  ],
};

export default sidebars;
