import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  // Documentation sidebar with logical grouping
  docsSidebar: [
    'index',

    // 1. Getting Started - Keep expanded for new users
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'getting-started'}],
    },

    // 2. Installation - Keep expanded for initial setup
    {
      type: 'category',
      label: 'Installation',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'installation'}],
    },

    // 3. Core Features - Collapsed group for main functionality
    {
      type: 'category',
      label: 'Core Features',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Email Accounts',
          collapsed: true,
          items: [{type: 'autogenerated', dirName: 'accounts'}],
        },
        {
          type: 'category',
          label: 'Sending Emails',
          collapsed: true,
          items: [{type: 'autogenerated', dirName: 'sending'}],
        },
        {
          type: 'category',
          label: 'Receiving Emails',
          collapsed: true,
          items: [{type: 'autogenerated', dirName: 'receiving'}],
        },
        {
          type: 'category',
          label: 'Webhooks',
          collapsed: true,
          items: [
            'webhooks/overview',
            'webhooks/webhook-routing',
            {
              type: 'category',
              label: 'Message Events',
              collapsed: true,
              items: [
                'webhooks/messagenew',
                'webhooks/messagesent',
                'webhooks/messagedeleted',
                'webhooks/messageupdated',
                'webhooks/messagemissing',
                'webhooks/messagedeliveryerror',
                'webhooks/messagefailed',
              ],
            },
            {
              type: 'category',
              label: 'Bounce & Complaint Events',
              collapsed: true,
              items: [
                'webhooks/messagebounce',
                'webhooks/messagecomplaint',
              ],
            },
            {
              type: 'category',
              label: 'Account Events',
              collapsed: true,
              items: [
                'webhooks/accountadded',
                'webhooks/accountdeleted',
                'webhooks/accountinitialized',
                'webhooks/authenticationerror',
                'webhooks/authenticationsuccess',
                'webhooks/connecterror',
              ],
            },
            {
              type: 'category',
              label: 'Mailbox Events',
              collapsed: true,
              items: [
                'webhooks/mailboxnew',
                'webhooks/mailboxdeleted',
                'webhooks/mailboxreset',
              ],
            },
            {
              type: 'category',
              label: 'Tracking & List Events',
              collapsed: true,
              items: [
                'webhooks/trackopen',
                'webhooks/trackclick',
                'webhooks/listunsubscribe',
                'webhooks/listsubscribe',
              ],
            },
            {
              type: 'category',
              label: 'Export Events',
              collapsed: true,
              items: [
                'webhooks/exportcompleted',
                'webhooks/exportfailed',
              ],
            },
          ],
        },
      ],
    },

    // 4. Configuration & Deployment - Collapsed group
    {
      type: 'category',
      label: 'Configuration & Deployment',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Configuration',
          collapsed: true,
          items: [{type: 'autogenerated', dirName: 'configuration'}],
        },
        {
          type: 'category',
          label: 'Deployment',
          collapsed: true,
          items: [{type: 'autogenerated', dirName: 'deployment'}],
        },
      ],
    },

    // 5. Integrations - Collapsed
    {
      type: 'category',
      label: 'Integrations',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'integrations'}],
    },

    // 6. API Reference - Collapsed with link to full API docs
    {
      type: 'category',
      label: 'API Reference',
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'api-reference'},
        {
          type: 'link',
          label: 'Complete API Documentation',
          href: '/docs/api/emailengine-api',
        },
      ],
    },

    // 7. Advanced & Reference - Collapsed group for advanced users
    {
      type: 'category',
      label: 'Advanced & Reference',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Advanced Topics',
          collapsed: true,
          items: [{type: 'autogenerated', dirName: 'advanced'}],
        },
        {
          type: 'category',
          label: 'Technical Reference',
          collapsed: true,
          items: [{type: 'autogenerated', dirName: 'reference'}],
        },
      ],
    },

    // 8. Help & Support - Merged from Troubleshooting, Support, Licensing, Comparisons
    {
      type: 'category',
      label: 'Help & Support',
      collapsed: true,
      items: [
        'troubleshooting/index',
        'support/security-faq',
        'support/index',
        'licensing/index',
        'comparison/emailengine-vs-nylas',
        'comparison/emailengine-vs-unipile',
      ],
    },

    // SEO Landing Pages - High-value keyword targets (bottom of sidebar)
    'email-api',
    'imap-api',
  ],

  // API Reference sidebar - manually structured by OpenAPI tags
  // Organized into collapsible groups based on API tags from swagger.json
  apiSidebar: [
    {
      type: 'doc',
      id: 'api/emailengine-api',
      label: 'API Overview',
    },
    {
      type: 'category',
      label: 'Account',
      collapsed: true,
      items: [
        'api/get-v-1-accounts',
        'api/get-v-1-changes',
        'api/get-v-1-account-account',
        'api/delete-v-1-account-account',
        'api/put-v-1-account-account',
        'api/get-v-1-account-account-oauthtoken',
        'api/get-v-1-account-account-serversignatures',
        'api/post-v-1-account',
        'api/post-v-1-verifyaccount',
        'api/post-v-1-authentication-form',
        'api/put-v-1-account-account-sync',
        'api/put-v-1-account-account-reconnect',
        'api/put-v-1-account-account-flush'
      ],
    },
    {
      type: 'category',
      label: 'Mailbox',
      collapsed: true,
      items: [
        'api/get-v-1-account-account-mailboxes',
        'api/post-v-1-account-account-mailbox',
        'api/delete-v-1-account-account-mailbox',
        'api/put-v-1-account-account-mailbox'
      ],
    },
    {
      type: 'category',
      label: 'Message',
      collapsed: true,
      items: [
        'api/get-v-1-account-account-messages',
        'api/get-v-1-account-account-text-text',
        'api/get-v-1-account-account-attachment-attachment',
        'api/get-v-1-account-account-message-message',
        'api/delete-v-1-account-account-message-message',
        'api/put-v-1-account-account-message-message',
        'api/get-v-1-account-account-message-message-source',
        'api/post-v-1-account-account-message',
        'api/post-v-1-account-account-search',
        'api/put-v-1-account-account-message-message-move'
      ],
    },
    {
      type: 'category',
      label: 'Submit',
      collapsed: true,
      items: ['api/post-v-1-account-account-submit'],
    },
    {
      type: 'category',
      label: 'Outbox',
      collapsed: true,
      items: [
        'api/get-v-1-outbox',
        'api/get-v-1-outbox-queueid',
        'api/delete-v-1-outbox-queueid'
      ],
    },
    {
      type: 'category',
      label: 'Delivery Test',
      collapsed: true,
      items: [
        'api/get-v-1-deliverytest-check-deliverytest',
        'api/post-v-1-deliverytest-account-account'
      ],
    },
    {
      type: 'category',
      label: 'Access Tokens',
      collapsed: true,
      items: [
        'api/get-v-1-tokens',
        'api/get-v-1-tokens-account-account',
        'api/post-v-1-token',
        'api/delete-v-1-token-token'
      ],
    },
    {
      type: 'category',
      label: 'Settings',
      collapsed: true,
      items: [
        'api/get-v-1-autoconfig',
        'api/get-v-1-settings',
        'api/post-v-1-settings',
        'api/get-v-1-settings-queue-queue',
        'api/put-v-1-settings-queue-queue'
      ],
    },
    {
      type: 'category',
      label: 'Templates',
      collapsed: true,
      items: [
        'api/get-v-1-templates',
        'api/get-v-1-templates-template-template',
        'api/delete-v-1-templates-template-template',
        'api/put-v-1-templates-template-template',
        'api/post-v-1-templates-template',
        'api/delete-v-1-templates-account-account'
      ],
    },
    {
      type: 'category',
      label: 'Logs',
      collapsed: true,
      items: ['api/get-v-1-logs-account'],
    },
    {
      type: 'category',
      label: 'Stats',
      collapsed: true,
      items: ['api/get-v-1-stats'],
    },
    {
      type: 'category',
      label: 'License',
      collapsed: true,
      items: [
        'api/get-v-1-license',
        'api/post-v-1-license',
        'api/delete-v-1-license'
      ],
    },
    {
      type: 'category',
      label: 'Webhooks',
      collapsed: true,
      items: [
        'api/get-v-1-webhookroutes',
        'api/get-v-1-webhookroutes-webhookroute-webhookroute'
      ],
    },
    {
      type: 'category',
      label: 'OAuth2 Applications',
      collapsed: true,
      items: [
        'api/get-v-1-oauth-2',
        'api/post-v-1-oauth-2',
        'api/get-v-1-oauth-2-app',
        'api/delete-v-1-oauth-2-app',
        'api/put-v-1-oauth-2-app',
        'api/get-v-1-pubsub-status'
      ],
    },
    {
      type: 'category',
      label: 'SMTP Gateway',
      collapsed: true,
      items: [
        'api/get-v-1-gateways',
        'api/get-v-1-gateway-gateway',
        'api/delete-v-1-gateway-gateway',
        'api/post-v-1-gateway',
        'api/put-v-1-gateway-edit-gateway'
      ],
    },
    {
      type: 'category',
      label: 'Blocklists',
      collapsed: true,
      items: [
        'api/get-v-1-blocklists',
        'api/get-v-1-blocklist-listid',
        'api/post-v-1-blocklist-listid',
        'api/delete-v-1-blocklist-listid'
      ],
    },
    {
      type: 'category',
      label: 'Multi Message Actions',
      collapsed: true,
      items: [
        'api/put-v-1-account-account-messages',
        'api/put-v-1-account-account-messages-move',
        'api/put-v-1-account-account-messages-delete'
      ],
    },
    {
      type: 'category',
      label: 'Export (Beta)',
      collapsed: true,
      items: [
        'api/post-v-1-account-account-export',
        'api/get-v-1-account-account-exports',
        'api/get-v-1-account-account-export-exportid',
        'api/get-v-1-account-account-export-exportid-download',
        'api/delete-v-1-account-account-export-exportid'
      ],
    },
  ],
};

export default sidebars;
